# Configuration for pre-commit hooks (see https://pre-commit.com/).
# Eventually the hooks described here will be run as tests before merging each PR.

# TODO: remove global exclusion of tests when testing overhaul is complete
exclude: ^test/

# Force all unspecified python hooks to run python 3.8
default_language_version:
  python: python3.8

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
    args: [--unsafe]
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude_types:
      - "markdown"
  - id: check-case-conflict
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args:
    - "--line-length=99"
    - "--target-version=py38"
  - id: black
    alias: black-check
    args:
    - "--line-length=99"
    - "--target-version=py38"
    - "--check"
    - "--diff"
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    alias: flake8-check
    args:
    - "--max-line-length=100"
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy
    args: [--allow-redefinition, --ignore-missing-imports]
